modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/RainLasea/BareBonesBrews/issues"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

displayURL="https://github.com/RainLasea/BareBonesBrews"

logoFile="icon.png"

authors="AbyssLasea"

description='''
Brew weaker versions of vanilla and modded potions in a heated water cauldron.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[15.10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[19.19,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="roughlyenoughitems"
    type="optional"
    versionRange="[16,17)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="emi"
    type="optional"
    versionRange="[1.1.24,2)"
    ordering="AFTER"
    side="CLIENT"
